#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="."
CONFIG_DIR="configs"
PROFILES_DIR="profiles"
PLUGINS_DIR="plugins"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git submodule update --init --recursive --remote

for config in ${@}; do
	configFile="$(mktemp)" ; echo -e "$(<"${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}")" > "$configFile"
	"${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
		-d "${BASE_DIR}" \
		-c "$configFile" \
		-p "${BASE_DIR}/${PLUGINS_DIR}/dotbot_plugin_aptget/aptget.py" \
		-p "${BASE_DIR}/${PLUGINS_DIR}/dotbot-sudo/sudo.py" \
		; rm -f "$configFile"
done
