- defaults:
    shell:
      stdout: true
      stderr: true
      stdin: true
- shell:
    - command: bash scripts/fish.install
      description: Install fish
    - command: sudo chsh -s /usr/bin/fish $(whoami)
      description: Set fish as default shell
