- defaults:
    shell:
      stdout: true
      stderr: true
      stdin: true
- shell:
    - command: sudo apt update && sudo apt install -y curl
      description: Install curl (dependency)
    - command: bash -c "env fish <(curl -fsSL https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install) --path=$HOME/.oh-my-fish --config=~/.config/oh-my-fish --noninteractive"
      description: Install OMF (Oh-My-Fish)
    - command: fish -c "omf install default"
      description: "Install OMF theme: Default"
    - command: fish -c "omf theme default"
      description: "Enable OMF theme: Default"
