- defaults:
    link:
      create: true
      relink: true
      force: true
- shell:
    - command: sudo apt-get install -y --no-install-recommends vim
      description: Install vim
- link:
    ~/.vimrc: dotfiles/vimrc
